-- VIZIT v2 core schema. Mobile clients only receive publishable keys; service-role access is server-only.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    first_name text not null default '',
    last_name text not null default '',
    display_name text not null default '',
    company text not null default '',
    job_title text not null default '',
    bio text not null default '',
    display_image_path text,
    contact_image_path text,
    logo_path text,
    public_slug text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_contacts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(user_id) on delete cascade,
    kind text not null check (kind in ('phone', 'email')),
    label text not null default '',
    value text not null,
    sort_order integer not null default 0,
    is_public boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_addresses (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(user_id) on delete cascade,
    label text not null default '',
    formatted_address text not null,
    sort_order integer not null default 0,
    is_public boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_links (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(user_id) on delete cascade,
    kind text not null default 'custom',
    label text not null default '',
    url text not null,
    sort_order integer not null default 0,
    is_public boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_settings (
    user_id uuid primary key references public.profiles(user_id) on delete cascade,
    is_public boolean not null default false,
    field_order jsonb not null default '[]'::jsonb,
    field_visibility jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.qr_settings (
    user_id uuid primary key references public.profiles(user_id) on delete cascade,
    default_mode text not null default 'profile' check (default_mode in ('profile', 'contact')),
    updated_at timestamptz not null default now()
);

create table if not exists public.nfc_settings (
    user_id uuid primary key references public.profiles(user_id) on delete cascade,
    include_contact_photo boolean not null default true,
    include_profile_url boolean not null default true,
    timeout_seconds integer not null default 60 check (timeout_seconds between 15 and 300),
    updated_at timestamptz not null default now()
);

create table if not exists public.share_events (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(user_id) on delete set null,
    event_name text not null check (event_name in (
        'profile_view',
        'nfc_share_started',
        'nfc_payload_read',
        'nfc_share_cancelled',
        'nfc_fallback_shown',
        'qr_opened',
        'qr_shared',
        'public_profile_opened',
        'contact_action',
        'ios_fallback_used'
    )),
    platform text,
    device_family text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists profile_contacts_user_order_idx on public.profile_contacts(user_id, sort_order);
create index if not exists profile_addresses_user_order_idx on public.profile_addresses(user_id, sort_order);
create index if not exists profile_links_user_order_idx on public.profile_links(user_id, sort_order);
create index if not exists share_events_user_created_idx on public.share_events(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.bootstrap_vizit_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles(user_id, display_name)
    values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
    on conflict (user_id) do nothing;

    insert into public.profile_settings(user_id) values (new.id)
    on conflict (user_id) do nothing;
    insert into public.qr_settings(user_id) values (new.id)
    on conflict (user_id) do nothing;
    insert into public.nfc_settings(user_id) values (new.id)
    on conflict (user_id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created_vizit on auth.users;
create trigger on_auth_user_created_vizit
after insert on auth.users
for each row execute procedure public.bootstrap_vizit_user();

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'profiles', 'profile_contacts', 'profile_addresses', 'profile_links',
        'profile_settings', 'qr_settings', 'nfc_settings'
    ] loop
        execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
        execute format(
            'create trigger set_%I_updated_at before update on public.%I for each row execute procedure public.set_updated_at()',
            table_name,
            table_name
        );
    end loop;
end;
$$;

alter table public.profiles enable row level security;
alter table public.profile_contacts enable row level security;
alter table public.profile_addresses enable row level security;
alter table public.profile_links enable row level security;
alter table public.profile_settings enable row level security;
alter table public.qr_settings enable row level security;
alter table public.nfc_settings enable row level security;
alter table public.share_events enable row level security;

create policy "profiles_owner_all" on public.profiles
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "profile_contacts_owner_all" on public.profile_contacts
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "profile_addresses_owner_all" on public.profile_addresses
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "profile_links_owner_all" on public.profile_links
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "profile_settings_owner_all" on public.profile_settings
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "qr_settings_owner_all" on public.qr_settings
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "nfc_settings_owner_all" on public.nfc_settings
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "share_events_owner_insert" on public.share_events
for insert to authenticated with check (auth.uid() = user_id);

revoke all on public.profiles from anon;
revoke all on public.profile_contacts from anon;
revoke all on public.profile_addresses from anon;
revoke all on public.profile_links from anon;
revoke all on public.profile_settings from anon;
revoke all on public.qr_settings from anon;
revoke all on public.nfc_settings from anon;
revoke all on public.share_events from anon;

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.profile_contacts to authenticated;
grant select, insert, update, delete on public.profile_addresses to authenticated;
grant select, insert, update, delete on public.profile_links to authenticated;
grant select, insert, update, delete on public.profile_settings to authenticated;
grant select, insert, update, delete on public.qr_settings to authenticated;
grant select, insert, update, delete on public.nfc_settings to authenticated;
grant insert on public.share_events to authenticated;

create or replace function public.get_public_profile(p_slug text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'slug', p.public_slug,
        'firstName', p.first_name,
        'lastName', p.last_name,
        'displayName', p.display_name,
        'company', p.company,
        'jobTitle', p.job_title,
        'bio', p.bio,
        'displayImagePath', p.display_image_path,
        'logoPath', p.logo_path,
        'contacts', coalesce((
            select jsonb_agg(jsonb_build_object(
                'kind', c.kind,
                'label', c.label,
                'value', c.value,
                'sortOrder', c.sort_order
            ) order by c.sort_order, c.id)
            from public.profile_contacts c
            where c.user_id = p.user_id and c.is_public
        ), '[]'::jsonb),
        'addresses', coalesce((
            select jsonb_agg(jsonb_build_object(
                'label', a.label,
                'value', a.formatted_address,
                'sortOrder', a.sort_order
            ) order by a.sort_order, a.id)
            from public.profile_addresses a
            where a.user_id = p.user_id and a.is_public
        ), '[]'::jsonb),
        'links', coalesce((
            select jsonb_agg(jsonb_build_object(
                'kind', l.kind,
                'label', l.label,
                'url', l.url,
                'sortOrder', l.sort_order
            ) order by l.sort_order, l.id)
            from public.profile_links l
            where l.user_id = p.user_id and l.is_public
        ), '[]'::jsonb)
    )
    from public.profiles p
    join public.profile_settings s on s.user_id = p.user_id
    where s.is_public
      and p.public_slug is not null
      and lower(p.public_slug) = lower(p_slug)
    limit 1;
$$;

revoke all on function public.get_public_profile(text) from public;
grant execute on function public.get_public_profile(text) to anon, authenticated;

insert into storage.buckets (id, name, public)
values
    ('profile-private', 'profile-private', false),
    ('profile-public', 'profile-public', true)
on conflict (id) do nothing;

create policy "profile_private_owner_select" on storage.objects
for select to authenticated
using (bucket_id = 'profile-private' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "profile_private_owner_insert" on storage.objects
for insert to authenticated
with check (bucket_id = 'profile-private' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "profile_private_owner_update" on storage.objects
for update to authenticated
using (bucket_id = 'profile-private' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'profile-private' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "profile_private_owner_delete" on storage.objects
for delete to authenticated
using (bucket_id = 'profile-private' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "profile_public_read" on storage.objects
for select to anon, authenticated
using (bucket_id = 'profile-public');
create policy "profile_public_owner_insert" on storage.objects
for insert to authenticated
with check (bucket_id = 'profile-public' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "profile_public_owner_update" on storage.objects
for update to authenticated
using (bucket_id = 'profile-public' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'profile-public' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "profile_public_owner_delete" on storage.objects
for delete to authenticated
using (bucket_id = 'profile-public' and (storage.foldername(name))[1] = auth.uid()::text);
