-- Forward-only privacy and integrity hardening for the VIZIT v2 core schema.
-- Keep the original core migration immutable because it may already be applied.

do $$
begin
    if exists (
        select 1
        from public.profiles
        where public_slug is not null
          and lower(btrim(public_slug)) !~ '^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$'
    ) then
        raise exception 'Invalid VIZIT public_slug values must be corrected before applying security hardening.';
    end if;

    if exists (
        select 1
        from public.profiles
        where public_slug is not null
        group by lower(btrim(public_slug))
        having count(*) > 1
    ) then
        raise exception 'Case-insensitive duplicate VIZIT public_slug values must be resolved before applying security hardening.';
    end if;
end;
$$;

update public.profiles
set public_slug = lower(btrim(public_slug))
where public_slug is not null
  and public_slug is distinct from lower(btrim(public_slug));

alter table public.profiles
    add constraint profiles_public_slug_format check (
        public_slug is null or public_slug ~ '^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$'
    );

create unique index profiles_public_slug_lower_idx
    on public.profiles(lower(public_slug))
    where public_slug is not null;

-- Privacy-safe defaults. Existing v2 rows are reset to private because the original defaults
-- could mark contact fields public without an explicit user decision.
update public.profile_contacts set is_public = false where is_public;
update public.profile_addresses set is_public = false where is_public;
update public.profile_links set is_public = false where is_public;

alter table public.profile_contacts alter column is_public set default false;
alter table public.profile_addresses alter column is_public set default false;
alter table public.profile_links alter column is_public set default false;

update public.profile_settings
set field_order = '[]'::jsonb
where jsonb_typeof(field_order) is distinct from 'array';

update public.profile_settings
set field_visibility = '{}'::jsonb
where jsonb_typeof(field_visibility) is distinct from 'object';

alter table public.profile_settings
    add constraint profile_settings_field_order_array
        check (jsonb_typeof(field_order) = 'array'),
    add constraint profile_settings_field_visibility_object
        check (jsonb_typeof(field_visibility) = 'object');

update public.qr_settings set default_mode = 'contact' where default_mode <> 'contact';
alter table public.qr_settings alter column default_mode set default 'contact';

update public.nfc_settings set timeout_seconds = 120 where timeout_seconds > 120;
alter table public.nfc_settings
    drop constraint if exists nfc_settings_timeout_seconds_check,
    add constraint nfc_settings_timeout_seconds_check
        check (timeout_seconds between 15 and 120);

alter table public.share_events
    add constraint share_events_metadata_object
        check (jsonb_typeof(metadata) = 'object') not valid,
    add constraint share_events_metadata_size
        check (octet_length(metadata::text) <= 4096) not valid;

create table public.legal_acceptances (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    privacy_policy_version text not null,
    terms_version text not null,
    accepted_at timestamptz not null default now(),
    constraint legal_acceptances_privacy_version_not_blank
        check (btrim(privacy_policy_version) <> ''),
    constraint legal_acceptances_terms_version_not_blank
        check (btrim(terms_version) <> ''),
    constraint legal_acceptances_version_unique
        unique (user_id, privacy_policy_version, terms_version)
);

alter table public.legal_acceptances enable row level security;

create policy "legal_acceptances_owner_select" on public.legal_acceptances
for select to authenticated using (auth.uid() = user_id);

revoke all on public.legal_acceptances from anon;
grant select on public.legal_acceptances to authenticated;

insert into public.legal_acceptances(
    user_id,
    privacy_policy_version,
    terms_version
)
select
    u.id,
    btrim(u.raw_user_meta_data ->> 'privacy_policy_version'),
    btrim(u.raw_user_meta_data ->> 'terms_version')
from auth.users u
where nullif(btrim(u.raw_user_meta_data ->> 'privacy_policy_version'), '') is not null
  and nullif(btrim(u.raw_user_meta_data ->> 'terms_version'), '') is not null
on conflict (user_id, privacy_policy_version, terms_version) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.bootstrap_vizit_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.profiles(user_id, display_name)
    values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
    on conflict (user_id) do nothing;

    insert into public.profile_settings(user_id) values (new.id)
    on conflict (user_id) do nothing;
    insert into public.qr_settings(user_id) values (new.id)
    on conflict (user_id) do nothing;
    insert into public.nfc_settings(user_id) values (new.id)
    on conflict (user_id) do nothing;

    insert into public.legal_acceptances(
        user_id,
        privacy_policy_version,
        terms_version
    )
    select
        new.id,
        btrim(new.raw_user_meta_data ->> 'privacy_policy_version'),
        btrim(new.raw_user_meta_data ->> 'terms_version')
    where nullif(btrim(new.raw_user_meta_data ->> 'privacy_policy_version'), '') is not null
      and nullif(btrim(new.raw_user_meta_data ->> 'terms_version'), '') is not null
    on conflict (user_id, privacy_policy_version, terms_version) do nothing;
    return new;
end;
$$;

create or replace function public.get_public_profile(p_slug text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
    select jsonb_strip_nulls(jsonb_build_object(
        'slug', p.public_slug,
        'firstName', case
            when s.field_visibility -> 'first_name' = 'true'::jsonb then p.first_name
        end,
        'lastName', case
            when s.field_visibility -> 'last_name' = 'true'::jsonb then p.last_name
        end,
        'displayName', case
            when s.field_visibility -> 'display_name' = 'true'::jsonb then p.display_name
        end,
        'company', case
            when s.field_visibility -> 'company' = 'true'::jsonb then p.company
        end,
        'jobTitle', case
            when s.field_visibility -> 'job_title' = 'true'::jsonb then p.job_title
        end,
        'bio', case
            when s.field_visibility -> 'bio' = 'true'::jsonb then p.bio
        end,
        'displayImagePath', case
            when s.field_visibility -> 'display_image' = 'true'::jsonb then p.display_image_path
        end,
        'logoPath', case
            when s.field_visibility -> 'company_logo' = 'true'::jsonb then p.logo_path
        end,
        'contacts', coalesce((
            select jsonb_agg(jsonb_build_object(
                'kind', c.kind,
                'label', c.label,
                'value', c.value,
                'sortOrder', c.sort_order
            ) order by c.sort_order, c.id)
            from public.profile_contacts c
            where c.user_id = p.user_id and c.is_public
        ), '[]'::jsonb),
        'addresses', coalesce((
            select jsonb_agg(jsonb_build_object(
                'label', a.label,
                'value', a.formatted_address,
                'sortOrder', a.sort_order
            ) order by a.sort_order, a.id)
            from public.profile_addresses a
            where a.user_id = p.user_id and a.is_public
        ), '[]'::jsonb),
        'links', coalesce((
            select jsonb_agg(jsonb_build_object(
                'kind', l.kind,
                'label', l.label,
                'url', l.url,
                'sortOrder', l.sort_order
            ) order by l.sort_order, l.id)
            from public.profile_links l
            where l.user_id = p.user_id and l.is_public
        ), '[]'::jsonb)
    ))
    from public.profiles p
    join public.profile_settings s on s.user_id = p.user_id
    where s.is_public
      and p.public_slug is not null
      and lower(p.public_slug) = lower(btrim(p_slug))
    limit 1;
$$;

revoke all on function public.get_public_profile(text) from public;
grant execute on function public.get_public_profile(text) to anon, authenticated;
